---
- name: install MongoDB
  hosts: mongodb1.rhdemo.local

  tasks:
  - name: add MongoDB repository
    yum_repository:
      name: mongodb-org-4.4
      description: MongoDB Repository Repo
      baseurl: http://repo.mangodb.org/yum/redhat/$releasever/mongodb-org/4.4/x86_64/
      gpgkey: https://www.mongodb.org/static/pgp/server-4.4.asc

  - name: install mongodb
    yum:
      name: mongodb-org
      state: present
      update_cache: yes

  - name: Enable MongoDB to run on boot
    service:
      name: mongod
      enabled: yes
      state: stared